db_file: "bot.db"

messages:
  responses:
    start: "Привет, дай мне доступ на свой Pocket аккаунт, для этого перейди поссылке:\n %s"
    already_authorized: "Ты уже авторизирован, другалек. Присылай ссылку."
    save_success: "Получилось! :) Ссылка добавлена."
    unknown_command: "Я не знаю, чего ты хочешь от меня"
  errors:
    default: "Произошла неизвестаная ошибка"
    invalid_url: "Невалидная ссылка, брат, перепроверь"
    unauthorized: "Зарегестрируйся, тебя нет в моей системе '/start' "
    unable_to_save: "Не получилось... :("

